// import { openPullRequest } from './github.js';
// import chalk from 'chalk';

// // after "✅ Fix applied and tests passed."
// console.log(chalk.cyan('Opening PR...'));
// const url = await openPullRequest({
//   branch,
//   title: `AI auto-fix: ${message || stack.split('\n')[0]}`,
//   body: `This PR was auto-generated by AI to fix:\n\n\`\`\`\n${message}\n\`\`\`\n\nStacktrace:\n\`\`\`\n${stack}\n\`\`\``
// });
// console.log(chalk.green(`✅ Pull Request created: ${url}`));
